import re
import sys
import os

VTT_PATH = "/root/assets/stock_karaoke_koplo/queue/salah_apa_adella/subs.id.vtt"
ASS_PATH = "/root/assets/stock_karaoke_koplo/queue/salah_apa_adella/karaoke.ass"

def vtt_time_to_cs(ts_str):
    # Format: HH:MM:SS.mmm or MM:SS.mmm
    parts = ts_str.split(":")
    if len(parts) == 3:
        h = int(parts[0])
        m = int(parts[1])
        s_parts = parts[2].split(".")
        s = int(s_parts[0])
        ms = int(s_parts[1]) if len(s_parts) > 1 else 0
    else:
        h = 0
        m = int(parts[0])
        s_parts = parts[1].split(".")
        s = int(s_parts[0])
        ms = int(s_parts[1]) if len(s_parts) > 1 else 0
    total_ms = h * 3600000 + m * 60000 + s * 1000 + ms
    return round(total_ms / 10)  # centiseconds

def cs_to_ass_time(cs):
    total_s = cs // 100
    rem_cs = cs % 100
    h = total_s // 3600
    rem_s = total_s % 3600
    m = rem_s // 60
    s = rem_s % 60
    return f"{h}:{m:02d}:{s:02d}.{rem_cs:02d}"

with open(VTT_PATH, "r", encoding="utf-8") as f:
    content = f.read()

# Pattern for cue blocks
blocks = content.split("\n\n")
cues = []

for b in blocks:
    lines = [l.strip() for l in b.strip().split("\n") if l.strip()]
    if not lines:
        continue
    time_line = None
    for l in lines:
        if "-->" in l:
            time_line = l
            break
    if not time_line:
        continue

    # Extract times
    m = re.match(r"(\d+:\d+:\d+\.\d+|\d+:\d+\.\d+)\s+-->\s+(\d+:\d+:\d+\.\d+|\d+:\d+\.\d+)", time_line)
    if not m:
        continue
    st_cs = vtt_time_to_cs(m.group(1))
    en_cs = vtt_time_to_cs(m.group(2))

    # Text lines after time line
    t_idx = lines.index(time_line)
    text_lines = lines[t_idx+1:]
    raw_text = " ".join(text_lines)

    # Bersihkan tag VTT dan token musik/bernyanyi
    clean_text = re.sub(r"<[^>]+>", "", raw_text)
    clean_text = clean_text.replace("[musik]", "").replace("[bernyanyi]", "").replace("[Musik]", "").replace("[Bernyanyi]", "").strip()

    if clean_text and len(clean_text) > 1:
        cues.append((st_cs, en_cs, clean_text))

# Gabungkan cue yang terlalu pendek atau berdekatan
merged = []
for st, en, txt in cues:
    if not merged:
        merged.append([st, en, txt])
        continue
    prev = merged[-1]
    if txt == prev[2]:
        # Teks sama berulang, perpanjang durasi
        prev[1] = max(prev[1], en)
    elif st - prev[1] < 50 and len(prev[2].split()) < 4:
        # Gabung kata yang berdekatan dalam 1 kalimat
        prev[1] = max(prev[1], en)
        prev[2] = (prev[2] + " " + txt).strip()
    else:
        merged.append([st, en, txt])

# Header ASS sesuai AGENTS.md Rule 11 (Font 76, Alignment 5 tengah layar, warna kuning berjalan)
ass_header = [
    "[Script Info]",
    "; Karaoke Subtitles generated by Cimoy 7-Agent Architecture",
    "Title: SALAH APA - Difarina Indra Ft. Fendik Adella (OM Adella)",
    "ScriptType: v4.00+",
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    "YCbCr Matrix: TV.601",
    "PlayResX: 1920",
    "PlayResY: 1080",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    "Style: Default,DejaVu Sans,76,&H0000FFFF,&H00FFFFFF,&H00151515,&H90000000,1,0,0,0,100,100,0,0,1,3,2,5,40,40,20,1",
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
]

dialogues = []
for st, en, txt in merged:
    dur_total = en - st
    if dur_total <= 0:
        continue
    words = txt.split()
    if not words:
        continue
    per_word_dur = max(1, dur_total // len(words))
    kf_text = "".join([f"{{\\kf{per_word_dur}}}{w} " for w in words]).strip()
    st_ass = cs_to_ass_time(st)
    en_ass = cs_to_ass_time(en)
    dialogues.append(f"Dialogue: 0,{st_ass},{en_ass},Default,,0,0,0,,{kf_text}")

with open(ASS_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(ass_header) + "\n" + "\n".join(dialogues) + "\n")

print(f"[✓] Berhasil membuat {len(dialogues)} baris lirik karaoke ke: {ASS_PATH}")
